version: '3.8'

services:
  app:
    build:
      context: .  # Путь, где находится Dockerfile (корневая папка проекта)
    container_name: my_python_app
    volumes:
      - ./docker_lab:/app  # Монтируем код в контейнер
      - ./docker_lab/venv:/app/venv  # Монтируем виртуальное окружение, если нужно
    environment:
      - DATABASE_URL=mysql://root:examplepassword@mysql_db:3306/mydb  # Указываем строку подключения к БД
      - OTHER_ENV_VARIABLE=some_value
    depends_on:
      - mysql_db
    command: alembic upgrade head && python /app/main.py  # Автоматическое выполнение миграций
    ports:
      - "8000:8000"  # Пробрасываем порты, если приложение работает на 8000 порту

  mysql_db:
    image: mysql:5.7  # Используем MySQL 5.7, можно выбрать другую версию
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword  # Пароль для root пользователя
      MYSQL_DATABASE: mydb  # Название базы данных
    ports:
      - "3307:3306"  # Пробрасываем порты для MySQL
    volumes:
      - mysql_data:/var/lib/mysql  # Храним данные MySQL на внешнем томе

volumes:
  mysql_data:
    driver: local
